workerThreads: 1
maxEventBufferCapacity: 50
eventBufferSize: 2000
clientTimeoutMin: 30
dataReceivers:
 thrift:
  tcpPort: 7611
  sslPort: 7711
 binary:
  tcpPort: 9611
  sslPort: 9711
  sslReceiverThreadPoolSize: 100
  tcpReceiverThreadPoolSize: 100


  
